#!/usr/bin/perl -CS

BEGIN {
	use File::Basename;
	push(@INC, dirname $0);
}

use Simurga;

my $command = shift @ARGV;

Simurga::connect_db();

add() if $command eq 'add';
all() if $command eq 'all';
move(@ARGV) if $command eq 'move';
sprice(@ARGV) if $command eq 'sprice';
csv(@ARGV) if $command eq 'csv';
scsv(@ARGV) if $command eq 'scsv';

Simurga::commit();


sub add
{
	my $data = {};
	$data->{'model_id'} = Simurga::prompt("Model serial number");
	$data->{'color_id'} = Simurga::Color->prompt->id;
	$data->{'material_id'} = Simurga::Material->prompt->id;
	$data->{'sizes'} = Simurga::prompt("Sizes (american, comma-separated)");
	$data->{'price_ru'} = Simurga::prompt("Price (RUR)");
	$data->{'desc_ru'} = Simurga::prompt_long("Description (russian, HTML allowed)");

	my $item = Simurga::ModelColor->create($data);
	print "Item id: " . $item->id . "\n";
}

sub csv
{
	my $file_name = shift;
	my $fd;
	open($fd, $file_name) || die $!;
	my $count = 0;
	my @lines = <$fd>;
	close($fd);

	my $colors = {};

	my $count;
	foreach my $line(reverse @lines)
	{
		chomp($line);
		my ($id, $color_name, $img1, $img2, $img3, $img4, $sizes, $price) = split(/;/, $line);
		$id += 0;
		next unless $id;

		$colors->{$color_name} = Simurga::Color->by_name($color_name) unless exists $colors->{$color_name};
		my $color = $colors->{$color_name};

		my $data = { 'model_id' => $id, 'color_id' => $color->id, 'sizes' => $sizes, 'price_ru' => $price,
			'material_id' => 1, # TODO
			'desc_ru' => '' };
		my $item = Simurga::ModelColor->create($data);

		$item->add_image($img1) if $img1 && -r $img1;
		$item->add_image($img2) if $img2 && -r $img2;
		$item->add_image($img3) if $img3 && -r $img3;
		$item->add_image($img4) if $img4 && -r $img4;

		$count++;
	}

	print "$count items imported.\n";
}

sub scsv
{
	my $file_name = shift;
	my $fd;
	open($fd, $file_name) || die $!;
	my $count = 0;
	my @lines = <$fd>;
	close($fd);

	my $count;
	foreach my $line(reverse @lines)
	{
		chomp($line);
		next unless $line;

		my ($art, $sprice) = split(/;/, $line, 2);
		my ($id, $color) = split(/-/, $arg, 2);

		my $item = Simurga::ModelColor->by_model_and_color($id, $color);
		if ($sprice ne '-' && $sprice)
		{
			$item->special_price_ru($sprice + 0);
		}
		else
		{
			$item->remove_special_price_ru();
		}
		$item->save();
	}
}

sub all
{
	my @items = Simurga::ModelColor->all;
	foreach my $item(@items)
	{
		print $item->id . " | " . $item->model_id . " | " . $item->model->name . " | " . $item->color->name . "\n";
	}
}

sub move
{
	my $from = shift(@_) + 0;
	my $to = shift(@_) + 0;
	Simurga::ModelColor->by_id($from)->move_to($to);
}

sub sprice
{
	my $art = shift;
	my $price = shift;
	my ($id, $color) = split(/-/, $art, 2);
	my $item = Simurga::ModelColor->by_model_and_color($id, $color);
	if ($price eq '-' || !$price)
	{
		$item->remove_special_price_ru;
	}
	else
	{
		$item->special_price_ru($price + 0);
	}
	$item->save;
}
