#!/usr/bin/perl -CS

BEGIN {
	use File::Basename;
	push(@INC, dirname $0);
}

use Simurga;

my $command = shift @ARGV;

Simurga::connect_db();

add() if $command eq 'add';
all() if $command eq 'all';
stitle(@ARGV) if $command eq 'stitle';
csv(@ARGV) if $command eq 'csv';

Simurga::commit();


sub add
{
	my $data = {};
	$data->{'id'} = Simurga::prompt("Serial number");
	$data->{'title_ru'} = Simurga::prompt("Title (in russian)");

	Simurga::Model->create($data);
}

sub csv
{
	my $file_name = shift;
	my $fd;
	open($fd, $file_name) || die $!;
	my $count = 0;
	foreach my $line(<$fd>)
	{
		chomp($line);
		my ($id, $short_title, $title) = split(/;/, $line);
		$id += 0;
		next unless $id;

		my $data = { 'id' => $id, 'title_ru' => $title, 'short_title_ru' => $short_title };
		Simurga::Model->create($data);
		$count += 1;
	}
	close($fd);

	print "$count models imported.\n";
}

sub all
{
	my @models = Simurga::Model->all;
	foreach my $model (@models)
	{
		print $model->id . " | " . $model->title_ru . "\n";
	}
}

sub stitle
{
	my $id = shift;
	my $model = Simurga::Model->by_id($id);
	$model->short_title_ru( Simurga::prompt("Short title (in russian)") );
	$model->save;
}
